// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerCore.DB;

namespace ServerCore.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20190429093008_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Models.ConnecedStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FromStationID");

                    b.Property<int?>("ToStationID");

                    b.HasKey("Id");

                    b.HasIndex("FromStationID");

                    b.HasIndex("ToStationID");

                    b.ToTable("ConnectedStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromStationID = 1,
                            ToStationID = 2
                        },
                        new
                        {
                            Id = 2,
                            FromStationID = 2,
                            ToStationID = 3
                        },
                        new
                        {
                            Id = 3,
                            FromStationID = 1,
                            ToStationID = 4
                        },
                        new
                        {
                            Id = 4,
                            FromStationID = 4,
                            ToStationID = 5
                        });
                });

            modelBuilder.Entity("Common.Models.EstimatedLanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EstimatedTime");

                    b.Property<int>("FlightNum");

                    b.Property<int>("PlaneID");

                    b.HasKey("Id");

                    b.HasIndex("PlaneID");

                    b.ToTable("EstimatedLanding");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstimatedTime = new DateTime(2019, 4, 29, 13, 10, 7, 729, DateTimeKind.Local).AddTicks(4719),
                            FlightNum = 123,
                            PlaneID = 1
                        },
                        new
                        {
                            Id = 2,
                            EstimatedTime = new DateTime(2019, 4, 29, 13, 0, 7, 738, DateTimeKind.Local).AddTicks(4120),
                            FlightNum = 103,
                            PlaneID = 2
                        },
                        new
                        {
                            Id = 3,
                            EstimatedTime = new DateTime(2019, 4, 29, 12, 50, 7, 738, DateTimeKind.Local).AddTicks(4139),
                            FlightNum = 23,
                            PlaneID = 3
                        });
                });

            modelBuilder.Entity("Common.Models.EstimatedTakeOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EstimatedTime");

                    b.Property<int>("FlightNum");

                    b.Property<int>("PlaneID");

                    b.HasKey("Id");

                    b.HasIndex("PlaneID");

                    b.ToTable("EstimatedTakeOff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstimatedTime = new DateTime(2019, 4, 29, 12, 35, 7, 739, DateTimeKind.Local).AddTicks(6322),
                            FlightNum = 222,
                            PlaneID = 4
                        },
                        new
                        {
                            Id = 2,
                            EstimatedTime = new DateTime(2019, 4, 29, 12, 40, 7, 739, DateTimeKind.Local).AddTicks(7581),
                            FlightNum = 111,
                            PlaneID = 5
                        });
                });

            modelBuilder.Entity("Common.Models.Plane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ReadyToMove");

                    b.HasKey("Id");

                    b.ToTable("Planes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ReadyToMove = true
                        },
                        new
                        {
                            Id = 2,
                            ReadyToMove = true
                        },
                        new
                        {
                            Id = 3,
                            ReadyToMove = false
                        },
                        new
                        {
                            Id = 4,
                            ReadyToMove = true
                        },
                        new
                        {
                            Id = 5,
                            ReadyToMove = false
                        });
                });

            modelBuilder.Entity("Common.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAvailable");

                    b.Property<int?>("PlaneID");

                    b.HasKey("Id");

                    b.HasIndex("PlaneID");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = true
                        });
                });

            modelBuilder.Entity("Common.Models.ConnecedStation", b =>
                {
                    b.HasOne("Common.Models.Station", "FromStation")
                        .WithMany()
                        .HasForeignKey("FromStationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Common.Models.Station", "ToStation")
                        .WithMany()
                        .HasForeignKey("ToStationID");
                });

            modelBuilder.Entity("Common.Models.EstimatedLanding", b =>
                {
                    b.HasOne("Common.Models.Plane", "Plane")
                        .WithMany()
                        .HasForeignKey("PlaneID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Common.Models.EstimatedTakeOff", b =>
                {
                    b.HasOne("Common.Models.Plane", "Plane")
                        .WithMany()
                        .HasForeignKey("PlaneID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Common.Models.Station", b =>
                {
                    b.HasOne("Common.Models.Plane", "Plane")
                        .WithMany()
                        .HasForeignKey("PlaneID");
                });
#pragma warning restore 612, 618
        }
    }
}
